### PR TITLE
#53 set expireAt as date, otherwise TTL index will not work

### PR DESCRIPTION
**Pull request by cyphercrack**
Fix for #53 set expireAt explicit as Date, bypassing problematic json <-> bson conversion, now the TTL index works as expected an can delete expired session documents

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@cyphercrack Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-session-data-mongodb&pullRequestId=58)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-session-data-mongodb&pullRequestId=58) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@cyphercrack Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-session-data-mongodb&pullRequestId=58)!

**Comment by gregturn** [comment]
Looks great @cyphercrack! Can you add some test cases to verify it works as expected?

**Comment by gregturn** [comment]
Resolved via https://github.com/spring-projects/spring-session-data-mongodb/commit/82cf365ba702d569013ce83940a6000933cfd3b6 and https://github.com/spring-projects/spring-session-data-mongodb/commit/54fa3f9d5859e3edcdce8470b2b2568ccaa33f3d.

**Comment by gregturn** [comment]
Thanks @cyphercrack!

**Comment by gregturn** [comment]
Resolved #53.

**Pull request closed without merging**
